# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "trendyol-yorum"
client_id = "dd67aa743351107e5ce305cbce8fdc0c"
application_url = "https://flexible-collected-hide-conversations.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://flexible-collected-hide-conversations.trycloudflare.com/auth/callback",
  "https://flexible-collected-hide-conversations.trycloudflare.com/auth/shopify/callback",
  "https://flexible-collected-hide-conversations.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ecomkinx.myshopify.com"
